apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: __SERVICE_NAME__
  namespace: flux-config
spec:
  chart:
    spec:
      version: __VERSION_TAG__
  values:
    environment: production
    name: __SERVICE_NAME__
    namespace: __TEAM_NAME__
    teamResourceGroupName: ${TEAM_RG}
    image: __VERSION__
    serviceAccount:
      name: __SERVICE_NAME__
    labels:
      component: web
    container:
      imagePullPolicy: Always
    ingress:
      class: nginx
      endpoint: __INGRESS_ENDPOINT__
      server: __ENVIRONMENT____ENV_INSTANCE__.adp.defra.gov.uk
    deployment:
      priorityClassName: default
    containerConfigMap:
      configServiceName: ${APPCONFIG_NAME}
      configServiceMIClientId: ${APPCONFIG_MI_CLIENTID}
      serviceMIClientId: ${clientId}
    storageAccountPrefix: ${STORAGEACCOUNT_PREFIX}
    enablePrivateEndpoint: ${ENABLE_PRIVATE_ENDPOINT}